# Generated by Django 5.2.5 on 2025-08-10 15:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Song title', max_length=200)),
                ('artist', models.CharField(help_text='Artist name', max_length=200)),
                ('audio_file', models.FileField(help_text='Upload MP3, WAV, or OGG file', upload_to='songs/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg'])])),
                ('lyrics_json', models.TextField(default='[]', help_text='Timed lyrics in JSON format: [{"time": 0, "text": "First line"}, {"time": 5, "text": "Second line"}]')),
                ('duration_seconds', models.IntegerField(default=180, help_text='Song duration in seconds (for admin timing control)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title', 'artist'],
            },
        ),
        migrations.CreateModel(
            name='SongRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100)),
                ('requester_email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, help_text='Optional message')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='karaoke.song')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
